# Use the Amazon Linux 2023 Lambda base image
FROM public.ecr.aws/lambda/provided.al2023

# Install the required Python version
RUN dnf install -y python3

# Copy the Python script into the container
COPY app.py ./

# Set the CMD to your handler (could be app.lambda_handler)
CMD ["app.lambda_handler"]